[package]
name = "cleaner"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
mutex = "1.0.2"
once_cell = "1.21.3"
walkdir = "2.5.0"

[workspace]
members = [
    "tools/cache_generator"
]
