[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
]

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"



[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
