[package]
name = "cache_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
num_cpus = "1.16"
rand = { version = "0.9.2", features = ["std_rng"] }
rand_chacha = "0.9.0"
chrono = { version = "0.4", features = ["serde"] }
